@host= http://localhost:3000

###
GET {{host}}/

###
GET {{host}}/api/users

###
GET {{host}}/api/users/UmG8sKmXmdW3MN0OEubn6

###
POST {{host}}/api/users
Content-Type: application/json

{
    "name": "Jaime",
    "lastname": "Escobedo",
    "username": "jrev",
    "password": "passwordJWoof",
    "phone": "3371026574",
    "email": "jaime@test.com",
    "city": "Guadalajara",
    "country": "Mexico",
    "zip": "44360",
    "state": "Jalisco"
}

###
DELETE {{host}}/api/users/cQpqT_3EGJqTpv4jOfke5


###
PUT {{host}}/api/users/EiZv5UaVWK2dM1Ny-V9Li
Content-Type: application/json

{
    "name": "Jaime",
    "lastname": "Escobedo",
    "username": "jrev",
    "password": "passwordJWoof",
    "phone": "3371026574",
    "email": "jaime@test.com",
    "city": "Guadalajara",
    "country": "Mexico",
    "zip": "44360",
    "state": "Jalisco"
}

//pets
###
GET {{host}}/api/pets

###
GET {{host}}/api/pets/NvqtJxSNcgf_rEvfV4w6r

###
GET {{host}}/api/pets?name=maik

###
POST {{host}}/api/pets/OuyQ3IKip9v0JDU13L-4O
Content-Type: application/json

{
    "name": "Dog1",
    "animal": "Dog",
    "age": 8,
    "temperment": "Sweet",
    "color": "Orange",
    "size": "Medium",
    "breed": "Golden",
    "gender": "Female",
    "health": "healthy",
    "castrated": true,
    "vaccinated": true,
    "image":
      "https://image.shutterstock.com/image-photo/red-male-cat-walking-towards-600w-138599810.jpg",
    "description": "completly wholesome boi",
    "date": "03-05-2022"
}

###
PUT {{host}}/api/pets/a90cpTq3HHWKONn8LUH87
Content-Type: application/json

{
    "age":9,
    "castrated":false
}

###
DELETE {{host}}/api/pets/a90cpTq3HHWKONn8LUH87

