@host= http://localhost:3000

###
GET {{host}}/

###
GET {{host}}/api/register

###
GET {{host}}/api/register/Vwbm6jtxXp6ZybI4zfjWV

###
POST {{host}}/api/register
Content-Type: application/json
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImlNbXZhaU9ia1BVWEJWdVVNSWdQUCIsImVtYWlsIjoiamVzc2ljYUB0ZXN0LmNvbSIsImlhdCI6MTY1MTYzMTE0NCwiZXhwIjoxNjUxNjMxNDQ0fQ.ugzOFJ3WjO3m_Wqf7ZnA18myKK4ZT2fWbPSTHapbqp8

{
    "name": "Jaime",
    "lastname": "Escobedo",
    "username": "jrev",
    "password": "passJWoof",
    "phone": "3361804527",
    "email": "jaime@test.com",
    "city": "Guadalajara",
    "country": "Mexico",
    "zip": "44360",
    "state": "Jalisco"
}

###
DELETE {{host}}/api/register/Vwbm6jtxXp6ZybI4zfjWV

###
PUT {{host}}/api/register/Vwbm6jtxXp6ZybI4zfjWV
Content-Type: application/json

{
    "name": "Jaime",
    "lastname": "Escobedo",
    "username": "Oss",
    "password": "passwordJWoof",
    "phone": "3371068269",
    "email": "jaime@test.com",
    "city": "Guadalajara",
    "country": "Mexico",
    "zip": "44360",
    "state": "Jalisco"
}


//Login
###
POST {{host}}/api/login
Content-Type: application/json

{
    "email":"jessica@test.com",
    "password":"passJSWoof"
}

//pets
###
GET {{host}}/api/pets

###
GET {{host}}/api/pets/NvqtJxSNcgf_rEvfV4w6r

###
GET {{host}}/api/pets?name=maik

###
POST {{host}}/api/pets/OuyQ3IKip9v0JDU13L-4O
Content-Type: application/json

{
    "name": "Dog1",
    "animal": "Dog",
    "age": 8,
    "temperment": "Sweet",
    "color": "Orange",
    "size": "Medium",
    "breed": "Golden",
    "gender": "Female",
    "health": "healthy",
    "castrated": true,
    "vaccinated": true,
    "image":
      "https://image.shutterstock.com/image-photo/red-male-cat-walking-towards-600w-138599810.jpg",
    "description": "completly wholesome boi",
    "date": "03-05-2022"
}

###
PUT {{host}}/api/pets/a90cpTq3HHWKONn8LUH87
Content-Type: application/json

{
    "age":9,
    "castrated":false
}

###
DELETE {{host}}/api/pets/a90cpTq3HHWKONn8LUH87


//CHAT

###
GET {{host}/api/chat

###
POST {{host}}/api/chat/ctXv5sWj9b2RjjlwGxDSR/otrouUisdjif5455641
Content-Type: application/json

{
    "msg": "of course"
}


###
PUT {{host}}/api/chat/deactivate/jV4NWN1FzkHqGCuluyH0g/jshai1235fd8s58


###
DELETE {{host}}/api/chat/ctXv5sWj9b2RjjlwGxDSR/6277d3bc42be41e74f31826c
